name: Testing actions

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  airtable:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-python@v5
        with:
          python-version: '3.8' 

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run the script
        id: runner
        run: python main.py

      - name: Echo var
        run: |
          echo "" && \
          echo ${{ steps.runner.name }}
